version: '2'
services:
  webapi:
    container_name: softstu_webapi
    build: 
      context: ../WebAPI
      dockerfile: ../docker/WebAPI.Dockerfile

    restart: unless-stopped
    ports: 
      - "7077:80"
    
    networks:
      - softstu-network
    
    command: ["dotnet", "software_studio_backend.dll"]

  mongoDB:
    container_name: softstu_mongo
    image: mongo:5.0.7
    volumes:
      - ../database:/data/db

    ports:
      - "27017:27017"

    restart: unless-stopped
    networks:
      - softstu-network

    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  nginx:
    container_name: softstu_nginx
    build: 
      context: ../
      dockerfile: docker/nginx.Dockerfile

    ports:
      - "80:80"

    restart: unless-stopped
    networks:
      - softstu-network

    environment:
      - NGINX_PORT=80
    

networks:
  softstu-network:
    name: softstu_network
    driver: bridge